### ISSUE TITLE
Inkplate6 color

### ISSUE THREAD

**Issue by abbottcam** [lanrat/homeplate#38]
hello

I think this has been asked before, but would you consider support for Inkplate6 color? Or know of anyone who has done it?

**Comment by lanrat** [comment]
Please see #31

**Comment by abbottcam** [comment]
https://github.com/brodykenrick/hass-inkplate-dashboards

**Comment by lanrat** [comment]
If anyone would want to submit a PR, I would likely accept it. But without the hardware myself, I can't build/test/debug it.
