### ISSUE TITLE
[Question] How does th partial screen updates work

### ISSUE THREAD

**Issue by Gloomyeye** [lanrat/homeplate#50]
I use the grayscale mode and notice that everytime the whole screen will be refreshed (I would say) and shows my home assistant dashboard. It is possible to only update a changed chart or something else with the partial screen update feature? The homeplate system could compare the last shwon image with the new image and only updates the changed parts. Is that possible?

**Comment by lanrat** [comment]
The partial screen update works by swapping the mode that the screen is working in, but only updating a small region of it at a time. You need to know the region to update and have only the data that changes already extracted. 

Currently this is only used for the status messages. If this was desired for the image, the esp32 would need a way to diff two images, find the changes, and break them into regions and then selectively apply them.

I think this may be possible but it would be very very slow and resource intensive on the esp32.
